# Generated by Django 4.2.7 on 2024-01-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.sucursal', verbose_name='Sucursal'),
        ),
    ]
