# Generated by Django 4.2.7 on 2024-01-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0002_alter_empleados_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(editable=False, max_length=8, verbose_name='Consecutivo'),
        ),
    ]
