# Generated by Django 4.2.7 on 2024-01-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0003_alter_factura_numero_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsucursal',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='inventario',
        ),
        migrations.AlterField(
            model_name='parametrosar',
            name='numero_fin',
            field=models.CharField(help_text='De valor puede ser 01 o el valor que se le fue asignado por el SAR', max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='parametrosar',
            name='numero_inicio',
            field=models.CharField(help_text='De valor puede ser 000 o el valor que se le fue asignado por el SAR', max_length=3, verbose_name='Punto de Establecimiento '),
        ),
    ]
