# Generated by Django 4.2.7 on 2024-01-05 18:35

import DistribuidoraCarne.validaciones
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0005_alter_facturaparametro_rango_final_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='facturaparametro',
            name='cai',
            field=models.CharField(help_text='Formato: XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX-XX', max_length=32, unique=True, validators=[DistribuidoraCarne.validaciones.validar_cai], verbose_name='Cai'),
        ),
        migrations.AlterField(
            model_name='facturaparametro',
            name='rango_final_factura',
            field=models.CharField(max_length=16, validators=[DistribuidoraCarne.validaciones.validar_rango_final], verbose_name='Rango Final Factura'),
        ),
    ]
