# Generated by Django 4.2.7 on 2024-01-05 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0006_alter_factura_hora_alter_facturaparametro_cai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='hora',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
