# Generated by Django 4.2.7 on 2024-02-20 17:33

import DistribuidoraCarne.validaciones
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0007_alter_factura_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategoria',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Categoría', 'verbose_name_plural': 'historical Categorías'},
        ),
        migrations.AddField(
            model_name='rutas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=150, validators=[DistribuidoraCarne.validaciones.validar_direccion], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=10, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='devoluciones',
            name='cantidad',
            field=models.IntegerField(validators=[DistribuidoraCarne.validaciones.validar_Cantidad], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='devoluciones',
            name='descripcion',
            field=models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='devoluciones',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(max_length=10, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='carro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.transporte', verbose_name='Vehiculo de Entrega'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[DistribuidoraCarne.validaciones.validar_direccion], verbose_name='Dirección de Entrega'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, validators=[DistribuidoraCarne.validaciones.validar_fecha_no_pasado], verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Estimada de Entrega'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(help_text='Consumidor Final', on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.metodospago', verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='facturaparametro',
            name='fecha_emision',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha Emisión'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='nombre',
            field=models.CharField(max_length=65, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='historicalclientes',
            name='direccion',
            field=models.CharField(max_length=150, validators=[DistribuidoraCarne.validaciones.validar_direccion], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='historicalclientes',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalclientes',
            name='telefono',
            field=models.CharField(max_length=10, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicaldescuento',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='telefono',
            field=models.CharField(max_length=10, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicalimpuesto',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalinventario',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalinventario',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_nivel_maximo_stock], verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='historicalinventario',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_nivel_minimo_stock], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='historicalmetodospago',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalmetodospago',
            name='nombre',
            field=models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre método de pago'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalsucursal',
            name='direccion',
            field=models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion], verbose_name='Dirección de la sucursal'),
        ),
        migrations.AlterField(
            model_name='historicalsucursal',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicalsucursal',
            name='telefono',
            field=models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono de la sucursal'),
        ),
        migrations.AlterField(
            model_name='historicaltipocargo',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_nivel_maximo_stock], verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_nivel_minimo_stock], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='metodospago',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='metodospago',
            name='nombre',
            field=models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre método de pago'),
        ),
        migrations.AlterField(
            model_name='parametrosar',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=10, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono de Empresa'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='ruta',
            field=models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Nombre Ruta'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=255, validators=[DistribuidoraCarne.validaciones.validar_direccion], verbose_name='Dirección de la sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono de la sucursal'),
        ),
        migrations.AlterField(
            model_name='tipocargo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='chofer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.empleados', verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='codigo',
            field=models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_placa_honduras], verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='nombre_carro',
            field=models.CharField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre del Vehiculo'),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.rutas', verbose_name='Ruta de Entrega'),
        ),
    ]
