# Generated by Django 4.2.7 on 2024-02-20 17:35

import DistribuidoraCarne.validaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0008_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='descripcion',
            field=models.TextField(blank=True, max_length=40, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
    ]
