# Generated by Django 4.2.7 on 2024-02-20 19:25

import DistribuidoraCarne.validaciones
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DistribuidoraCarne', '0009_alter_rutas_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='id_producto',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_cotizacion',
            field=models.DateField(auto_now=True, validators=[DistribuidoraCarne.validaciones.validar_fecha_actualizacion], verbose_name='Fecha de Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='DistribuidoraCarne.clientes', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='descripcion',
            field=models.TextField(blank=True, max_length=70, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('tiene_descuento', models.BooleanField(default=False, verbose_name='Tiene Descuento')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.cotizacion', verbose_name='Cotización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotizaciones',
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='productos',
            field=models.ManyToManyField(through='DistribuidoraCarne.DetalleCotizacion', to='DistribuidoraCarne.producto', verbose_name='Productos'),
        ),
    ]
