# Generated by Django 4.2.7 on 2024-02-20 19:50

import DistribuidoraCarne.validaciones
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DistribuidoraCarne', '0011_alter_cotizacion_fecha_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='tiene_descuento',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[DistribuidoraCarne.validaciones.validar_valor_impuesto]),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[DistribuidoraCarne.validaciones.validar_Cantidad], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_cotizacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='productos',
            field=models.ManyToManyField(through='DistribuidoraCarne.DetalleCotizacion', to='DistribuidoraCarne.inventario', verbose_name='Productos'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.cotizacion', verbose_name='Cotizacion'),
        ),
        migrations.AlterField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.inventario'),
        ),
    ]
