# Generated by Django 4.2.7 on 2024-02-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0013_detallecotizacion_usuario_alter_cotizacion_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='parametros',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DistribuidoraCarne.facturaparametro'),
        ),
    ]
