# Generated by Django 4.2.7 on 2024-02-20 23:56

import DistribuidoraCarne.validaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0014_cotizacion_parametros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Descuento'),
        ),
        migrations.AlterField(
            model_name='devoluciones',
            name='descripcion',
            field=models.TextField(max_length=50, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='historicalclientes',
            name='apellido',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='historicalclientes',
            name='nombre',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalclientes',
            name='telefono',
            field=models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicaldescuento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicaldescuento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Descuento'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='apellido',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='nombre',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='telefono',
            field=models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='historicalimpuesto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalimpuesto',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Impuesto'),
        ),
        migrations.AlterField(
            model_name='historicalmetodospago',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalmetodospago',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre método de pago'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalsucursal',
            name='ciudad',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Ciudad de la sucursal'),
        ),
        migrations.AlterField(
            model_name='historicalsucursal',
            name='nombre',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Sucursal'),
        ),
        migrations.AlterField(
            model_name='historicaltipocargo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='historicaltipocargo',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre del Cargo'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='nombre',
            field=models.CharField(default='Identidad', max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre del documento'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Impuesto'),
        ),
        migrations.AlterField(
            model_name='metodospago',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='metodospago',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre método de pago'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Teléfono de Empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_contacto',
            field=models.CharField(max_length=8, validators=[DistribuidoraCarne.validaciones.validar_telefono], verbose_name='Numero de Contacto'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Ciudad de la sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Sucursal'),
        ),
        migrations.AlterField(
            model_name='tipocargo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=50, null=True, validators=[DistribuidoraCarne.validaciones.validar_descripcion], verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tipocargo',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre del Cargo'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(default='Identidad', max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre del documento'),
        ),
    ]
