# Generated by Django 4.2.7 on 2024-02-21 00:01

import DistribuidoraCarne.validaciones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistribuidoraCarne', '0015_alter_categoria_descripcion_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='nombre',
            field=models.CharField(max_length=20, unique=True, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre Descuento'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalcategoria',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='historicalclientes',
            name='apellido',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='historicalclientes',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicaldescuento',
            name='nombre',
            field=models.CharField(db_index=True, max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre Descuento'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='apellido',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='historicalempleados',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalimpuesto',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre Impuesto'),
        ),
        migrations.AlterField(
            model_name='historicalmetodospago',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre método de pago'),
        ),
        migrations.AlterField(
            model_name='historicalsucursal',
            name='ciudad',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Ciudad de la sucursal'),
        ),
        migrations.AlterField(
            model_name='historicalsucursal',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Sucursal'),
        ),
        migrations.AlterField(
            model_name='historicaltipocargo',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre del Cargo'),
        ),
        migrations.AlterField(
            model_name='historicaltipodocumento',
            name='nombre',
            field=models.CharField(default='Identidad', max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre del documento'),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre Impuesto'),
        ),
        migrations.AlterField(
            model_name='metodospago',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre método de pago'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=12, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_contacto',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre de Contacto'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='ciudad',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Ciudad de la sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=20, validators=[DistribuidoraCarne.validaciones.validar_nombre], verbose_name='Nombre Sucursal'),
        ),
        migrations.AlterField(
            model_name='tipocargo',
            name='nombre',
            field=models.CharField(max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre del Cargo'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(default='Identidad', max_length=15, validators=[DistribuidoraCarne.validaciones.validar_nombre_titular], verbose_name='Nombre del documento'),
        ),
    ]
